### ISSUE TITLE
Card "cross-reference"

### ISSUE THREAD

**Issue by natevw** [adambrault/kerblam#10]
Mostly it might just be further clarifying https://github.com/adambrault/kerblam/issues/2 at this point, but as far as I understand, this is meant to be played with a custom set of cards and the standard deck is filling in for test play.

So it might be helpful to have a can't-miss-it sort of master table that lays out "eventual X kerblam card -> use N playing card instead". Here's my understanding so far:

| Kerblam | Solitaire |
| --- | --- |
| General | King |
| Medic | Queen |
| Sniper | Ace |
| Spy | Jack |
| Nuke | Joker (or other unused card) |
| Soldier | Pip cards (including ace) |
| Nation | ??? |
| unused | [??? some of the pip cards?] |

<del>And also: there's no pre-sorting of the deck, just shuffle and deal? So one player could end up with multiple generals? Or do you divide suits first?</del><ins>Oh, I see each player gets a deck of their own. So I'm guessing they do get multiple of each officers as they turn up into their hand.</ins>

**Comment by adamavenir** [comment]
I originally had easy reference cheat sheets, but then we changed some of the rules. I don't know where the original illustrator files are, so i'll make some new ones soon based on current rules and upload those.

In the interim, I'll do just as you say and create some low-fi text based ones in the readme.

**Comment by adamavenir** [comment]
To your question, the game was originally designed to be played with regular cards, and this can quite easily be done and people seem to get the hang quickly. 

But custom cards make this far simpler, since the instructions for playing and point values can go on the card. So that's the intent once we spin up a good enough round of tests to determine we're comfortable with the final rule set.

**Comment by adamavenir** [comment]
Added a reference sheet PDF
