### ISSUE TITLE
Recommendations 

### ISSUE THREAD

**Issue by ccwscott** [adambrault/kerblam#3]
Player elimination is tricky in a game.  Almost all modern games try to avoid this mechanic because no one likes to sit on their hands and watch other people play.  Most even try to find ways to hide who is in the lead and who is behind, so everyone can still hold out hope for the victory until final scores are totaled.

Along similar lines, the game seems designed as what is often called a "king maker".  Where the victor or loser in the game comes down to who gets attacked the most.

Luck seems to overwhelm all other factors in this game.  Mostly it comes down to what you roll and what you draw, there aren't that many significant decisions to make in the game.

There seems to be danger of run away victories, where someone who draws well right away has a tendency to do better and better, where someone not doing well will struggle to recover.  Whoever has the lowest OP will tend to be the target of attacks, and then has a hard time retreating as well.  The person doing the worst will be the target of attacks, because they are closer to having zero population, and closer to getting their attacker a bonus draw from the graveyard.  There might be room for some kind of mechanic of "overextending" your army, and more incentives to go after the stronger players instead of the weaker.  

Do you get no units on your front line until the end of your first turn?

Consider working on the balance of the cards.  Right now officers give you both special powers and break ties and their powers just pile up the more you get.  Try to create more substantial choices to make in the game.  Cards that do more, different things.  Maybe some cards are buildings and let you draw more or player more soldiers or give you bonuses in battle, or defense, or offense, or damage your enemies in different ways.  Consider ways to force players to "spread out the pain" so one player can't get picked on too much, likes nukes hitting all players or something, and consider making the dice rolls not have such a widely varying effects in terms of how powerful they are.

**Comment by adamavenir** [comment]
@ccwscott Thank you so much for this!

A key design goal was not leaving people sitting on their hands and to make the endgame dramatic, even if you've been eliminated. Some of the less obvious (or less documented) game mechanics change this.

>  Luck seems to overwhelm all other factors in this game. Mostly it comes down to what you roll and what you draw, there aren't that many significant decisions to make in the game.

There is a significant amount of strategy that is not obvious here—and those strategies increase dramatically as you go above 3 players. I have played maybe around 100 games and the remarkable thing that I have really enjoyed in playing this game over time is that as much as it seems one person is dominating at various points, the outcomes have surprised me more often than not, and I have seen several different strategies along the way.

Let me explain a few things that might not be obvious because they could be poorly explained or because some of the dynamics aren't apparent until playing a few games.

---

**Nuclear weapons become a very real deterrent.** If people know (or suspect) someone has a nuke in their hand, they tend to shy away from attacking them—and they're guaranteed to wince a little when they do.

**Kerblams can be game-changing equalizers.** The Kerblam is a nuke that is available to the player when they are entirely out of civilians. Outcomes of these nukes can make it so the perceived "loser" can actually win the game—or at _least_ cause the player who has been in the lead all game to lose. As you can see, there is a high reward for finishing off a player. But as a player runs out of cards and has access to their Kerblam nuke, all other players become very intimidated of them.

---

> Right now officers give you both special powers and break ties and their powers just pile up the more you get.

But keep in mind that absolutely everyone is playing with the same set of cards and that by drawing those powerful cards into their hand, they are now _exposed_.

> There might be room for some kind of mechanic of "overextending" your army, and more incentives to go after the stronger players instead of the weaker.

This is exactly what happens, in fact. Though players have to be cautious about how they go after the strongest players—which is often where some of the special powers come in.

The neat thing that I've found in the game is that your strengths also become your weaknesses. If you have a high OP total, you're likely to have others want to nuke you or to snipe your generals. Who has the "most powerful army" swings wildly from round to round.

It's an interesting balance because you _want_ to have a lot of cards in play because you become more powerful, but you also have to strike as soon as you can, but that once again exposes you to countermeasures by whomever you're attacking, which could include a nuke that wipes out your great army.

As you suggested, overextending the army is already a real mechanic and it plays a pivotal role.

---

> Cards that do more, different things.

My goal is to have a simple and easy to learn core game and then add complexity with various optional packages.

We have already done this with "Nation" cards, which I haven't documented here yet. This is easily my favorite part of the game. These cards add some very ridiculous dynamics. You choose a nation at the beginning of the game and that nation gives you some different powers, most of which are very powerful, but only usable one time in the game.

I think we might add a strategy deck or something which would do as you say—allow you to draw more players or perform some unique move.

> nukes hitting all players

This is a very interesting idea. Thanks for that! Perhaps when a nuke is played against a single player, there is some lesser damage that applies to everyone. I'll try to work that in and see how it goes.

---

> Do you get no units on your front line until the end of your first turn?

Note this line under [Getting started](https://github.com/adambrault/kerblam/blob/master/README.md#getting-started):

> Everyone draws 10 cards to begin with, laying down Front Line cards (red) and keeping Covert Forces (black and all nukes) in your hand, out of sight."

and step #6 under [Turn progression](https://github.com/adambrault/kerblam/blob/master/README.md#turn-progression): 

> Any player in the game who has less than 10 total cards in their entire Army must draw from their Civilian Deck until they do (or draw as many cards as you can, if you have less than 10 in your Civilian Deck). 

I added the following line to this, just to add further clarification:

> Whenever you draw any new cards in the game, put all non-nuke red cards on your Front Line and keep the other cards (black and all nukes) in your hand as Covert Forces.

---

I would really love to hear your thoughts on all the above, as well as any other ideas you have. :)

Thank you!

**Comment by adamavenir** [comment]
Closing this just for housekeeping purposes, but I would be grateful for any more thoughts you have in this thread or in new issues.

Based on this feedback, I made a few clarifications to the docs and opened an issue for nukes affecting more players (#8) and one for adding a strategy deck (#9)

**Comment by ccwscott** [comment]
Sounds good!  Seems like I should probably play it before theorizing too much more.  

There's a guy in the Columbia Basin Boardgame Society that has published two card games: Prism, and the Escape from Alcatraz version of Mystery Rummy.  The people at CBBS are super nice people and could help playtest and offer comments as well.  They do a bunch of public events throughout the week.
